### ISSUE TITLE
Log parameters for each draw in SEIR code

### ISSUE THREAD

**Issue by jkamins7** [HopkinsIDD/COVIDScenarioPipeline#117]

**Comment by jcblemai** [comment]
True that. In a folder with one file per sim or a file with everything ?

**Comment by jlessler** [comment]
I think the latter would be better if possible, but I assume 1 file per sim is easier to implement?

**Comment by jkamins7** [comment]
i think it might be the same to implement

**Comment by jcblemai** [comment]
Closed when moving to parquet
