### ISSUE TITLE
Adjust documentation to reflect changes in SEIR mobility stuff.

### ISSUE THREAD

**Issue by jlessler** [HopkinsIDD/COVIDScenarioPipeline#124]

**Comment by jcblemai** [comment]
Here is an update to be pandoc'd
[update_tex.txt](https://github.com/HopkinsIDD/COVIDScenarioPipeline/files/4453359/update_tex.txt)

**Comment by eclee25** [comment]
Added a slightly modified version of mobility and SEIR description to report_devel branch RMD chunk
