### ISSUE TITLE
Is there an explanation for the underlying model formulation 

### ISSUE THREAD

**Issue by ashwin-varma97** [HopkinsIDD/COVIDScenarioPipeline#131]
Hey everyone, 

I'm just wondering if there is a paper or doc somewhere which describes the underlying model specification used in this model so I can read it as I consider using this model to capacity plan in for a group of hospitals.

**Comment by jkamins7** [comment]
The underlying simulation model is a stochastic compartmental SEIR with an erlang distribution for recovery.  There are references in the report.generation package, but I think they might be for model parameters rather than for the model as a whole

**Comment by eclee25** [comment]
The report.generation package also has a description of the model specification in `R/pkgs/report_generation/inst/rmarkdown/chunks/SEIRModelDesc.Rmd`

**Comment by jcblemai** [comment]
Hi,

I'm sorry we're seriously lacking behind in documentation. As you may have observed, the code is build around several modules: the epidemiological model, the hospitalization model, the report generation module and others...

I attached a (very badly written) description of the epidemiological model. It's a spatial, stochastic SEIR model. The hospital model is based on branching probabilities and delays from log normal distributions that you can parametrize in a config file. For this, you might want to download [this file)](https://github.com/HopkinsIDD/COVIDScenarioPipeline/blob/master/vignettes/how_to.html) to understand the flow If you have any question or need help please do.

**Comment by jkamins7** [comment]
@ashwin-varma97 , can i mark this issue as closed, or do you need more information?

**Comment by vineetmp** [comment]
I found this [preprint](https://www.medrxiv.org/content/10.1101/2020.06.11.20127894v1.full.pdf) document referenced [here](https://github.com/HopkinsIDD/COVID19_Minimal/wiki) to be really useful for understanding the model in detail!
