### ISSUE TITLE
Clarification of the column name in the model output csv file in the hospitalization folder.

### ISSUE THREAD

**Issue by SteveLeungYL** [HopkinsIDD/COVIDScenarioPipeline#154]
Hi everyone, great works here!
Can you have a clarification of the model output csv file generated in the hospitalization folder? 
I am not sure the column meaning of **incidl**, **hosp_curr**, **icu_curr**, **vent_curr**, **incidH**, **incidICU**, **incidVent**, **incidD**, **date_inds**, **sim_num_good**, **geo_ind**. 
Some explanation of these columns would be much appreciated. :-)

**Comment by jkamins7** [comment]
in general there are outcomes
 - Incidence (I)
 - Hospitalizations (H)
 - ICU admissions (ICU)
 - Ventilators (vent)

At both incidence (incid) and/or prevalence (_curr).  Most of the columns are of a combination of those two.  For the other two columns, sim_num_good is unused (always 1) and geo_ind is the id of the place (as specified in the geodata.csv)
