### ISSUE TITLE
Fix bug in load_cum_inf_geounit_dates  

### ISSUE THREAD

**Issue by eclee25** [HopkinsIDD/COVIDScenarioPipeline#198]
Seems to be in multiple branches... not sure when or how it got introduced but it's returning empty dataframes

**Comment by jkamins7** [comment]
is this bug fixed now?

**Comment by hrmeredith12** [comment]
Not yet. Working on it this afternoon.

**Comment by eclee25** [comment]
fixed DataLoadFuncs.R and merged into dataseed
