### ISSUE TITLE
Fix ICU stay duration numbers

### ISSUE THREAD

**Issue by jkamins7** [HopkinsIDD/COVIDScenarioPipeline#2]

**Comment by salauer** [comment]
As mentioned earlier: ICU parameters of log(8.25), log(2.2), give a mean of 11, median of 8.25 and IQR of 4.8-14.0, which are similar to https://www.medrxiv.org/content/10.1101/2020.03.02.20030452v1.full.pdf+html

I don't know all the places these parameters need to go though.

**Comment by jkamins7** [comment]
The parameters we changed were not the right ones

**Comment by jkamins7** [comment]
@Keeganlt @shauntruelove and i looked at these and we all agreed
