### ISSUE TITLE
Update build us setup to use tidycensus

### ISSUE THREAD

**Issue by eclee25** [HopkinsIDD/COVIDScenarioPipeline#248]

**Comment by eclee25** [comment]
Need to make sure this includes one geoid per territory
American Samoa	            AS	60000
Guam	                         GU	66000
Northern Mariana Islands	MP	69000
Puerto Rico   	            PR	72000
Virgin Islands	            VI	78000

**Comment by kkintaro** [comment]
Code is written.

Waiting for git-lfs to be added to Docker.
