### ISSUE TITLE
Create filter shows up in makefile even when make makefile is run on a config without dynfilter_path

### ISSUE THREAD

**Issue by eclee25** [HopkinsIDD/COVIDScenarioPipeline#261]
I think the correct behavior would be to exclude the call to create_filter.R in the makefile

This is on master branch

**Comment by hrmeredith12** [comment]
I commented out the dynfilter_path line in my config file, but when I ran make_makefile.R, the create_filter portion of the pipeline was still included. To get things to work, I commented out:

```
#.files/10_filter: .files/directory_exists .files/10_importation
#	$(RSCRIPT) $(PIPELINE)/R/scripts/create_filter.R -c $(CONFIG)
#	touch .files/10_filter
```
and deleted all instances of `.files/10_filter` (every time time simulate.py was run)

`.files/10_simulation_1918Influenza_UK_degrade: .files/directory_exists  **.files/10_filter** .files/10_importation`
