### ISSUE TITLE
The model runs without warning if the sum of all mobility from a region is greater than the region's population

### ISSUE THREAD

**Issue by scnerd** [HopkinsIDD/COVIDScenarioPipeline#339]
While the mobility code checks that in the mobility matrix, any entry m_{i,j} < pop_i, it doesn't check that the sum of the row is less than the population, sum_j(m_{i,j}) < pop_i. The code uses this sum to compute the proportion of people that commute, and uses 1 minus that value for the local exposure. Hence, if the row's sum is greater than the population, then you get a negative local exposure without any warning or error for the odd behavior we'd expect from this.

**Comment by eclee25** [comment]
Warning added to dev_make
