### ISSUE TITLE
setup.py missing

### ISSUE THREAD

**Issue by trevorsweeney** [HopkinsIDD/COVIDScenarioPipeline#355]
![step 8](https://user-images.githubusercontent.com/29664250/88388736-19792100-cd83-11ea-93fb-70c768ceb169.png)
![file missing](https://user-images.githubusercontent.com/29664250/88388774-2ac22d80-cd83-11ea-868a-db89b4071ff2.png)

there's a setup.py found in SEIR directory though, is this the correct file?

**Comment by eclee25** [comment]
No.

@jkamins7 @jcblemai Were we using setup.py install on `master` branch or as it still a direct installation with the requirements.txt file? Weird that the setup.py is not on master.

**Comment by jkamins7** [comment]
setup.py is not in master.  we are not using it in master.  where is this mentioned in the documentation?

**Comment by jcblemai** [comment]
We're now providing gempyor with the toml file, following PEP518
