### ISSUE TITLE
Census API Key

### ISSUE THREAD

**Issue by trevorsweeney** [HopkinsIDD/COVIDScenarioPipeline#356]
bit confused here.  

LFS isn't in the docker container? What census api key is required?

![](https://user-images.githubusercontent.com/29664250/88389098-ceabd900-cd83-11ea-9725-11fac5294311.png)

**Comment by eclee25** [comment]
Git LFS is installed in the Docker. The `git lfs install` initializes the hooks to the repository.

You need to get access to a US Census API key: https://api.census.gov/data/key_signup.html
