### ISSUE TITLE
(question) Have the disease parameter values changed over time in the model runs?

### ISSUE THREAD

**Issue by jloewy724** [HopkinsIDD/COVIDScenarioPipeline#361]
We have been tracking projected hospitalizations of the Scenario Pipeline at the county level through [Calcat](https://calcat.covid19.ca.gov/cacovidmodels/), who we believe pulls the values from your own running of the model. Two parameters we are interested in knowing as examples:

1. We have seen the length of stay of our COVID patients decreasing over time
2. Our "percent of infected patients requiring hospitalization" decreases as our testing capacity has increased

Have the disease parameter values (as opposed to data directly sourced, like cases and hospitalizations) being plugged in to the model been changing over time? Is it possible for us to view the associated values for a given run of the model?

**Comment by eclee25** [comment]
Thanks for your interest in our model. The model parameters themselves are not time-varying in the model simulations but it is possible to plug in new parameters based on new information that arises. For specifics about model runs that appear on CalCAT, I would encourage you to reach out to CDPH directly.
