### ISSUE TITLE
Fix hard coded path to "COVIDScenarioPipeline/local_install.R" in inference_runner.sh

### ISSUE THREAD

**Issue by shauntruelove** [HopkinsIDD/COVIDScenarioPipeline#477]
Code has hard coding to run 
`Rscript COVIDScenarioPipeline/local_install.R` in the inferecne_runner.sh script. but if you set COVIDScenarioPipeline to be anything else (like CSP) when loading it all to docker, it breaks.

**Comment by jcblemai** [comment]
Fixed in #484
