### ISSUE TITLE
covidcommon config.R has inexplicable setting of config

### ISSUE THREAD

**Issue by jlessler** [HopkinsIDD/COVIDScenarioPipeline#65]
I don't understand why this is here but not changing it in cases I am being dumb....

##'
##'Map of configuration values, constructed via a call to `load_config`
##'
config <- NA

**Comment by jkamins7** [comment]
I think this is so the config defaults to NA if not defined.  Not sure this is a behaviour we want, but it's now addressed in tests. Closing this issue
