### ISSUE TITLE
Remove geographic setup from the pipeline repo

### ISSUE THREAD

**Issue by jcblemai** [HopkinsIDD/COVIDScenarioPipeline#78]
Might be confusing. Many things in data/ do not belong there and are outdated

**Comment by jkamins7** [comment]
can you elaborate on this?  I'm not sure I understand which part of the repo the geographic setup is

**Comment by jcblemai** [comment]
<img width="1090" alt="Screenshot 2020-04-04 at 15 28 58" src="https://user-images.githubusercontent.com/7485811/78452001-18639d00-7689-11ea-8d0d-d04470c96a6d.png">

> only united-states-commutes, age severity should stay here. The script should go to a setup-creation folder with the new USA script

**Comment by jcblemai** [comment]
This has been done
