### ISSUE TITLE
SEIR.py - Mobility should be accounted in a more rigorous way

### ISSUE THREAD

**Issue by eclee25** [HopkinsIDD/COVIDScenarioPipeline#90]
this is a less pressing issue than the mobility matrix indexes

**Comment by jcblemai** [comment]
I changed the name:

- Do we want to  account for it as a change in the FOI, performing a matrix multiplication
- Something "commutery" with night and day ?
- binomial and multinomial draw as. now, in a robust way ?

**Comment by jkamins7** [comment]
i think maybe let's schedule some time to think about this.  I think we should talk it out rather than just decide.  There are different meanings to each possible answer here.
