### ISSUE TITLE
Develop set input data templates for other countries to follow and post in Covid minimal

### ISSUE THREAD

**Issue by eclee25** [HopkinsIDD/COVIDScenarioPipeline#92]
In particular, what format do we want surveillance data to come in for filtering?

**Comment by jkamins7** [comment]
what does this mean?

**Comment by eclee25** [comment]
States and countries want to know how they should structure the confirmed case count data that will be used for filtering in the model

**Comment by jkamins7** [comment]
I think now we have a point where once build_US_setup.R is integrated into the pipeline there will be no need for setup.  Though, it currently uses the 2010 data

**Comment by jkamins7** [comment]
I think @kkintaro and @jwills are interested in this issue as it relates some to integration testing.

**Comment by jkamins7** [comment]
Is this issue still ongoing?  Is what we have sufficient? If not, what more do we need?
